spring:
  application:
    name: spring-redis
  cache:
    type: redis
  redis:
    # use localhost if you're running redis locally
    # use redis if you're running redis in a docker
    host: ${REDIS_HOST}
    port: 6379
    password:
    jedis:
      pool:
        max-total: 16
        min-idle: 4
        max-idle: 8


server:
  port: 8080

#URL to see the swagger/open API 3.0 in motion use http://localhost:8080/swagger-ui.html
springdoc:
  api-docs:
    path: /api-docs



